subsystems:
	$(MAKE) -C 6
	$(MAKE) -C 7
	$(MAKE) -C 8
	$(MAKE) -C 9
	$(MAKE) -C 10
	$(MAKE) -C 12

clean:
	$(MAKE) -C 6 clean
	$(MAKE) -C 7 clean
	$(MAKE) -C 8 clean
	$(MAKE) -C 9 clean
	$(MAKE) -C 10 clean
	$(MAKE) -C 12 clean
